### ISSUE TITLE
启动mj机器人成功以及成功登录微信，但返回错误信息

### ISSUE THREAD

**Issue by dfggggx198601** [yangjian102621/chatgpt-plus-exts#2]
关于mj
        2023-09-22T12:12:42.727Z        INFO    mj/bot.go:64    Starting MidJourney Bot successfully!
          2023-09-22T12:12:43.692Z        ERROR   mj/bot.go:86    消息推送失败，Network Err: 
            Post"http://localhost:5678/api/mj/notify": dial tcp [::1]:5678: connect: connection refused, Http Err: Post 
           "http://localhost:5678/api/mj/notify": dial tcp [::1]:5678: connect: connection refused, Resp Err:
            日志就一直重复上面的消息推动失败
关于微信：
微信登录成功后，我尝试收入了0.01元，就一直弹出2023-09-22T14:59:10.197Z        ERROR   weixin/bot.go:75        消息推送失败：<nil><nil>Not Authorized
查看api容器的日志，提示[0.988ms] [rows:0] SELECT * FROM `chatgpt_chat_items` WHERE chat_id='7bdfdb65-3a1a-44bf-9d58-4d13047f5e58' AND `chatgpt_chat_items`.`deleted_at` IS NULL ORDER BY `chatgpt_chat_items`.`id` LIMIT 1

**Comment by yangjian102621** [comment]
仔细阅读一下部署教程，需要配置跟 chatgpt-plus 项目通信的 token，这个报错也给你明确提示了。
![image](https://github.com/yangjian102621/chatgpt-plus-exts/assets/4746061/85be76a4-cf00-4ded-9ddc-a56f7c781394)

**Comment by dfggggx198601** [comment]
mj的绘画功能还是无法使用，我已经按照说明，配置了midjourneyconfig项下的所有参数，也配置好了callbacktoken,查看容器的logs，最后一行也是2023-09-30T15:08:07.033Z        INFO    mj/bot.go:64    Starting MidJourney Bot successfully!，但在网页触发绘画任务时，该容器并没有反应，discord里的机器人也是离线状态
![image](https://github.com/yangjian102621/chatgpt-plus-exts/assets/104133292/390a03c9-d694-4aef-8f0c-ad4c9ff37cb2)

**Comment by yangjian102621** [comment]
检查一下时候是你的机器人权限不够，需要有发消息和读取历史消息的权限。
